// 비즈니스 로직(서비스의 핵심 로직)
// 상품 관련 API
export class ProductService {
  checkSoldout = () => {
    console.log("판매가 완료되었는지 검증한다");
    // 2. 상품의 판매 여부 검증하는 코드(대략 10줄 정도. 상품이 팔렸는지 아닌지 검증)
    // ...
    // ...
    // ...
    // ...
  };
}
